export const guides = [
  {
    id: 'html',
    order: 1,
    title: 'HTML',
    summary: '给网页内容安排清晰的结构。',
    icon: 'code',
    intro: 'HTML 是网页的结构层。标题、段落、图片和按钮会被写成不同的元素，让浏览器知道每块内容是什么。',
    why: '当 AI 生成的页面结构混乱时，你需要先判断问题出在内容层级，还是样式与交互。认识 HTML，才能把修改说得具体。',
    steps: ['先写页面最重要的标题', '按阅读顺序放入段落、图片和操作', '用语义合适的元素表达每一块内容'],
    example: '<main>\n  <h1>周末创作沙龙</h1>\n  <p>一起完成第一个作品。</p>\n  <a href="#signup">立即报名</a>\n</main>',
    question: '如果要表达页面上最重要的标题，优先使用哪个元素？',
    options: ['<h1>', '<div>', '<span>'],
    answer: 0,
    feedback: '<h1> 表示页面的主标题，它比只负责分组的 <div> 更能表达内容结构。',
  },
  {
    id: 'css',
    order: 2,
    title: 'CSS',
    summary: '控制网页的排版、颜色和视觉层级。',
    icon: 'paint',
    intro: 'CSS 决定内容如何呈现，包括字体、间距、颜色、布局以及不同屏幕上的变化。',
    why: '页面“能用但不好看”时，问题通常不在 HTML。把视觉目标拆成字号、留白、对齐和颜色，AI 才能稳定修改。',
    steps: ['先建立少量颜色和间距变量', '从页面整体布局开始，再处理局部细节', '同时检查鼠标、键盘和移动端状态'],
    example: ':root {\n  --brand: #1769e8;\n  --space: 1.5rem;\n}\n\n.hero {\n  max-width: 72rem;\n  margin: auto;\n  padding: var(--space);\n}',
    question: '想统一修改整站主色，哪种方式更容易维护？',
    options: ['每个按钮单独改颜色', '使用 CSS 变量保存主色', '把颜色写进图片'],
    answer: 1,
    feedback: 'CSS 变量能让多个组件共享同一颜色值，换主题时只需修改一处。',
  },
  {
    id: 'responsive-design',
    order: 3,
    title: '响应式设计',
    summary: '让页面在手机和电脑上都能顺畅使用。',
    icon: 'device',
    intro: '响应式设计会根据可用空间调整布局、字号和交互，而不是把桌面页面等比例缩小。',
    why: '很多 AI 页面只在生成时的视口好看。真正上线前，要检查窄屏换行、触控区域、图片尺寸和横向溢出。',
    steps: ['先让内容在窄屏自然排列', '在空间足够时增加列数', '用真实手机尺寸检查主要任务'],
    example: '.guide-list {\n  display: grid;\n  grid-template-columns: 1fr;\n}\n\n@media (min-width: 800px) {\n  .guide-list { grid-template-columns: 1fr 1fr; }\n}',
    question: '手机页面出现横向滚动条时，第一步应该做什么？',
    options: ['隐藏所有内容', '找到超出视口的具体元素', '缩小整个页面'],
    answer: 1,
    feedback: '先定位哪个元素溢出，再修正它的宽度、内边距或换行规则，避免掩盖问题。',
  },
  {
    id: 'domain',
    order: 4,
    title: '域名',
    summary: '给网站一个便于记忆和访问的地址。',
    icon: 'globe',
    intro: '域名是用户输入的地址。DNS 记录负责把这个名字指向真正提供网页内容的服务。',
    why: '部署平台给出的临时地址适合测试；正式运营时，自有域名方便迁移、建立品牌，也能配置统一的 HTTPS。',
    steps: ['选择容易读写的域名', '在托管平台添加自定义域名', '按平台提示配置 DNS 并等待生效'],
    example: '用户访问 qizhan.example\n        ↓\nDNS 查询目标地址\n        ↓\n托管平台返回网页',
    question: 'DNS 记录的主要作用是什么？',
    options: ['编写网页样式', '把域名指向对应服务', '保存用户密码'],
    answer: 1,
    feedback: 'DNS 负责名称与服务地址之间的解析，不负责页面代码或账号数据。',
  },
  {
    id: 'deployment',
    order: 5,
    title: '部署',
    summary: '把本地网页发布为别人能访问的版本。',
    icon: 'cloud',
    intro: '部署会把经过构建和检查的产物上传到托管环境，并为它提供稳定的公开地址。',
    why: '本地能打开不代表线上可用。环境变量、路由刷新、缓存、HTTPS 和后端地址都会在部署阶段暴露问题。',
    steps: ['执行生产构建并处理错误', '在预览环境走完核心流程', '发布后重新检查域名、移动端和刷新'],
    example: '源代码 → npm run build → dist 产物 → 托管平台 → 公网地址',
    question: '部署后详情页刷新变成 404，最可能需要检查什么？',
    options: ['单页应用的路由回退规则', '显示器亮度', '编辑器主题'],
    answer: 0,
    feedback: '客户端路由需要服务器把对应路径交回应用入口，否则直接刷新时服务器找不到文件。',
  },
  {
    id: 'git',
    order: 6,
    title: 'Git',
    summary: '记录项目变化，让修改可比较、可恢复。',
    icon: 'branch',
    intro: 'Git 会记录一组文件在不同时间点的变化。一次清晰的提交应该表达一个完整、可理解的修改。',
    why: '让 AI 大范围改代码前，先保存当前可用状态。出现问题时，你可以查看差异并恢复具体文件，而不是重做整个项目。',
    steps: ['修改前查看工作区状态', '完成一个小目标后检查差异', '验证通过再创建说明清晰的提交'],
    example: 'git status\ngit diff\ngit add src/\ngit commit -m "Add responsive guide list"',
    question: '准备让 AI 改动多个文件前，哪项习惯最有帮助？',
    options: ['先保存一个可用版本', '删除项目历史', '关闭所有测试'],
    answer: 0,
    feedback: '一个清晰的可用版本能让后续差异更容易审查，也能在出错时提供恢复点。',
  },
  {
    id: 'accessibility',
    order: 7,
    title: '可访问性',
    summary: '让更多人可以理解并操作你的网站。',
    icon: 'person',
    intro: '可访问性关注不同能力和设备条件下的使用体验，例如键盘操作、文字对比、替代文本和清晰标签。',
    why: '无障碍不是上线后的装饰。语义结构和可见焦点做好后，键盘用户、屏幕阅读器用户以及临时受限的用户都会受益。',
    steps: ['不用鼠标走一遍核心流程', '检查每个输入是否有清晰标签', '确保焦点可见且文字对比足够'],
    example: '<label for="email">邮箱</label>\n<input id="email" type="email" autocomplete="email">',
    question: '一个只有图标的按钮至少需要补充什么？',
    options: ['更大的阴影', '可被辅助技术识别的名称', '自动播放声音'],
    answer: 1,
    feedback: '图标没有文字时，需要通过可访问名称说明按钮作用，例如 aria-label。',
  },
  {
    id: 'forms',
    order: 8,
    title: '表单',
    summary: '收集并检查用户主动提交的信息。',
    icon: 'form',
    intro: '表单由标签、输入控件、校验提示和提交动作组成。它需要明确告诉用户该填什么、哪里出错、是否提交成功。',
    why: '报名、联系和登录都依赖表单。只做出输入框还不够，还要处理空值、格式错误、等待状态与重复提交。',
    steps: ['为每个字段提供可见标签', '提交前校验必要格式', '展示等待、成功和错误状态'],
    example: '<form>\n  <label for="name">姓名</label>\n  <input id="name" name="name" required>\n  <button type="submit">提交报名</button>\n</form>',
    question: '提交请求进行中时，按钮应该怎样处理？',
    options: ['保持可重复点击', '暂时禁用并显示处理状态', '立刻清空页面'],
    answer: 1,
    feedback: '明确的等待状态能减少重复提交，也让用户知道系统正在处理。',
  },
];

// 使用无原型对象：避免 /guide/constructor、/guide/__proto__ 这类路径命中
// Object.prototype 上的继承属性，从而绕过「找不到就显示 404」的判断并导致渲染崩溃。
const guideMap = Object.create(null);
for (const guide of guides) guideMap[guide.id] = guide;
export const guideById = guideMap;

export function findGuide(id) {
  return Object.hasOwn(guideById, id) ? guideById[id] : undefined;
}
