// 术语别名（「也常被叫作」）—— 从原站 catalog 数据提取，2026-09-17。
// 中文页展示全部；英文页只展示纯 ASCII 别名（原站行为，过滤后为空则不渲染该区块）。
export const termAliases = {
  "ab-test": ["AB 测试","A/B Testing","Split Test","分流实验","对照实验"],
  "acceptance-criteria": ["验收条件","AC","验收准则"],
  "accessibility": ["可访问性","a11y","无障碍设计"],
  "active": ["按下态","激活态",":active"],
  "agent-loop": ["Agentic Loop","智能体循环"],
  "ai-agent": ["智能体","智能代理","Agent"],
  "ai-basics": ["生成式 AI 基础","LLM 应用基础"],
  "ai-hallucination": ["模型幻觉","Hallucination","AI 编造"],
  "animation": ["动效","CSS 动画","关键帧动画"],
  "api": ["API 接口","应用程序编程接口"],
  "api-key": ["接口密钥","服务密钥","Access Key","Secret Key","Token"],
  "api-proxy": ["中转站","API 中转","反向代理","Relay","Reverse Proxy"],
  "app-icon": ["应用程序图标","App 图标","application icon"],
  "atomicity": ["原子操作","不可分割性","Atomic"],
  "audit-log": ["操作日志","安全审计日志","审计记录"],
  "authentication": ["登录认证","Auth","JWT","JWT 认证","用户登录"],
  "auto-complete": ["AutoComplete","自动补全","输入建议"],
  "back-top": ["BackTop"],
  "backpressure": ["反压"],
  "blue-green-deployment": ["Blue-Green Deployment","Blue/Green Deployment","蓝绿发布","红黑部署"],
  "border-radius": ["圆角","边角弧度","胶囊角"],
  "box-model": ["盒模型","盒子模型","box-sizing"],
  "browser-devtools": ["DevTools","开发者工具","浏览器开发工具"],
  "browser-storage": ["客户端存储","本地存储","Web Storage","localStorage","sessionStorage"],
  "build": ["Build","项目构建","打包"],
  "button": ["操作按钮"],
  "cache": ["HTTP 缓存","缓存副本"],
  "canary-release": ["Canary Release","Canary Deployment","金丝雀部署","灰度发布"],
  "canonical-url": ["规范 URL","rel=canonical"],
  "cd": ["CD","Continuous Delivery","Continuous Deployment","持续交付","持续部署","CI/CD"],
  "cdn": ["CDN 加速","内容分发网络"],
  "chart": ["数据图表","可视化图表","Data Visualization"],
  "chat-ui": ["聊天 UI","聊天窗口","Chat Interface"],
  "ci": ["CI","Continuous Integration","持续集成"],
  "circuit-breaker": ["断路器","熔断机制","服务熔断"],
  "collapse": ["可折叠面板"],
  "color-picker": ["ColorPicker","色彩选择器"],
  "component": ["UI 组件","界面组件","UI Component"],
  "config-file": ["设置文件","配置项","config.json","config.toml"],
  "context-engineering": ["Context Management","上下文管理"],
  "context-window": ["上下文长度","Context Length"],
  "contract-testing": ["Contract Test","接口契约测试","契约校验"],
  "contrast": ["颜色对比","明暗对比","前景背景对比"],
  "conversation-history": ["聊天记录","消息历史"],
  "conversion-funnel": ["漏斗分析","Funnel Analysis","转化路径","Conversion Funnel Analysis"],
  "cookie": ["HTTP Cookie","浏览器 Cookie","网页 Cookie"],
  "coroutine": ["纤程","轻量级线程","用户态线程"],
  "cors": ["跨源资源共享","跨域资源共享","Cross-Origin Resource Sharing"],
  "crud": ["增删改查","CRUD 操作","数据的四种基本操作"],
  "css": ["层叠样式表","Cascading Style Sheets"],
  "cta": ["行动号召","核心行动入口","转化按钮","Call to Action"],
  "cursor": ["光标"],
  "dark-mode": ["暗色模式","夜间模式","深色主题","Dark Theme"],
  "data-type": ["字段类型","数据格式"],
  "database-migration": ["DB Migration","Schema Migration","数据库版本管理","数据库表迁移"],
  "database-write": ["落库","写库","数据库写入","数据持久化"],
  "date-picker": ["DatePicker"],
  "design-token": ["设计变量","Design Tokens"],
  "distributed-system": ["分布式架构","分布式集群","分布式计算"],
  "dns": ["DNS 解析","域名系统"],
  "dom": ["Document Object Model","文档对象模型树"],
  "drawer": ["抽屉组件","侧边滑出面板","侧边抽屉"],
  "dropdown": ["操作菜单","更多菜单"],
  "e2e-test": ["E2E","链路测试","跨端测试"],
  "easing": ["动效曲线","动画曲线","Easing Curve"],
  "enqueue": ["入列","进队","推入队列","投递任务"],
  "entitlement": ["Entitlements","订阅权益","功能解锁","付费权限","Feature Entitlement"],
  "faq": ["常见问题","Frequently Asked Questions"],
  "favicon": ["浏览器网站图标","标签页图标","site icon"],
  "feature-flag": ["Feature Flag","Feature Toggle","Feature Gate","功能旗标","特性开关","功能门禁"],
  "field": ["表单字段","数据字段","信息项"],
  "file": ["文件卡片","文件列表项"],
  "filter": ["筛选条件","过滤","内容筛选"],
  "flaky-test": ["Flaky Test","不稳定用例","间歇性失败测试"],
  "flex": ["弹性盒","弹性布局","Flexbox","Flex布局"],
  "focus": ["聚焦态","焦点状态",":focus"],
  "gantt-chart": ["Gantt","甘特排期","甘特图表","Gantt Diagram"],
  "git": ["Git 版本控制","版本控制"],
  "grid": ["网格布局","栅格布局","Grid布局","CSS Grid"],
  "harness-engineering": ["Agent Harness Engineering","Agent Harness","智能体脚手架工程"],
  "hash": ["哈希值","散列","散列函数","内容哈希","文件指纹"],
  "header": ["网站页头","站点页头","Site Header"],
  "heuristic-evaluation": ["启发式检查","可用性走查","专家走查","启发式评价"],
  "hook": ["钩子","事件钩子","自动化钩子","Git Hook"],
  "hover": ["鼠标悬停","悬停态",":hover"],
  "html": ["HTML 页面结构","超文本标记语言"],
  "http": ["HTTP 请求","超文本传输协议"],
  "https": ["安全连接","HTTPS 连接"],
  "human-in-the-loop": ["HITL","Human in the Loop","人工介入","人类监督","人机协同确认","关键节点人工审批"],
  "icon": ["界面图标","功能图标"],
  "idempotency": ["幂等性","幂等处理","幂等设计","幂等键"],
  "image": ["图像","图片组件"],
  "import-export": ["导入","导出","数据导入导出"],
  "input": ["文本输入框","单行输入框"],
  "input-number": ["InputNumber","数字步进器","Numeric Stepper"],
  "integration-test": ["Integration Test","集成测"],
  "javascript": ["JS"],
  "json": ["JSON 数据","JavaScript Object Notation"],
  "label": ["字段标签","输入标签"],
  "lease": ["租约机制"],
  "lint": ["Lint","Linter","代码检查","静态检查"],
  "load-testing": ["压测","性能测试","容量测试","负载压测"],
  "lock": ["互斥锁","排他锁","并发锁","分布式锁"],
  "logo": ["品牌标志","品牌 Logo","wordmark"],
  "margin": ["外边距","外留白","间距"],
  "markdown": ["Markdown 文档","MD 文档","Markdown 文件"],
  "masonry-layout": ["瀑布流布局","Masonry 布局","Masonry Layout"],
  "mcp": ["模型上下文协议","MCP协议","MCP Server","MCP Client","MCP 服务器"],
  "message-consumer": ["消息消费者","队列消费者","Worker 进程","订阅者"],
  "message-queue": ["MQ","Message Broker","消息中间件","消息代理","异步任务队列"],
  "modal": ["弹窗","模态窗","对话框","模态框","Dialog"],
  "monitoring": ["Monitoring","生产监控","应用监控"],
  "moodboard": ["灵感板","风格拼贴","氛围板"],
  "multi-instance": ["多实例","多副本部署","集群部署","水平扩展部署"],
  "multimodal": ["多模态 AI","多模态模型","Multimodality"],
  "mvp": ["最小可行产品","Minimum Viable Product","最小可行版本","最小化可行产品"],
  "navbar": ["导航栏","主导航栏"],
  "nextjs": ["Next"],
  "not-found-page": ["404 页面","404 Not Found"],
  "npm": ["包管理","Node 包管理"],
  "open-graph": ["OG","og 标签","分享元数据"],
  "openai-compatible-api": ["兼容接口","OpenAI 格式接口","ChatCompletions 兼容"],
  "overflow": ["内容溢出","溢出截断","溢出隐藏"],
  "padding": ["内边距","内留白","内边留白"],
  "page-metadata": ["网页元数据","head 信息","meta 信息"],
  "permission-mode": ["审批模式","权限策略","自主执行级别","安全模式"],
  "placeholder": ["占位符","输入框提示文字","输入提示"],
  "plugin": ["扩展","IDE 扩展","编辑器插件","Extension"],
  "pointer": ["数据指针","内存指针","分支指针","HEAD 指针"],
  "popconfirm": ["气泡确认框","就近确认框","行内确认"],
  "port": ["端口号","Port Number","localhost 端口"],
  "postgresql": ["Postgres","PG","PostgreSQL 数据库","Postgres 数据库"],
  "prd": ["产品需求文档","Product Requirements Document","产品需求","需求文档"],
  "process": ["操作系统进程","系统进程","后台进程","PID"],
  "product-backlog": ["产品积压","产品待办","Backlog","Product Backlog Item","PBI"],
  "product-discovery": ["产品探索","需求探索","Product Discovery Phase","需求发现","机会评估"],
  "product-roadmap": ["产品规划路线图","Roadmap","Agile Roadmap","路线图"],
  "profile": ["配置预设","配置组","配置文件预设","环境档案"],
  "progress": ["进度指示器"],
  "project-rules": ["AGENTS.md","CLAUDE.md","项目规范","Agent 指南","Cursor Rules"],
  "prompt": ["提示词工程","Prompt Engineering","AI提示词","Prompt Template","提示词模板","Few-shot Prompting"],
  "provider": ["模型服务商","模型平台","API 提供商","AI 供应商"],
  "python": ["Py"],
  "quality-gate": ["Quality Gates","代码门禁","发布门禁","PR 门禁","CI 门禁"],
  "quote": ["引文","引用块"],
  "race-condition": ["竞态","竞争条件","时序竞争","并发竞态"],
  "rate-limit": ["限流","请求频率限制"],
  "react": ["React.js"],
  "react-pattern": ["ReAct 机制","Reason + Act","推理行动模式"],
  "redirect": ["URL 重定向","跳转"],
  "regression-test": ["Regression Test","回归检查"],
  "response-speed": ["TTFT 与 TPS","TTFT & TPS","首 Token 延迟","每秒 Token 数"],
  "responsive-design": ["响应式","自适应布局","CSS Media Query","媒体查询","响应式网页设计","自适应设计","Responsive Web Design","断点","Breakpoint","像素断点"],
  "robots-txt": ["robots 文件","Robots Exclusion Protocol"],
  "rollback": ["Rollback","版本回滚","回退"],
  "route": ["路由","Endpoint","API Endpoint","接口端点"],
  "sandbox": ["隔离沙盒","安全沙箱","沙盒环境","隔离容器"],
  "search": ["站内搜索","关键词搜索","内容搜索"],
  "segmented": ["分段选择器","Segmented Control"],
  "select": ["下拉选择框","Select Box"],
  "seo": ["搜索引擎优化","Search Engine Optimization"],
  "serverless": ["Serverless 函数","无服务器计算"],
  "shadcn-ui": ["shadcn"],
  "shadow": ["阴影","盒阴影","投影","box-shadow"],
  "side-effect": ["附带效应","副作用操作","外部影响","状态变更"],
  "single-instance": ["单实例","单机部署","单节点部署","单副本部署"],
  "single-page-layout": ["单页布局","长页面","Single Page Layout"],
  "skill": ["技能","Agent Skill","技能包","Agent 技能","SKILL.md"],
  "skip-link": ["SkipLink","跳到主内容","Skip to content"],
  "smoke-test": ["冒烟测试","主流程冒烟","基线可用性测试"],
  "social-proof": ["社会认同","从众背书","信任证据","用户见证"],
  "sort": ["排序方式","升序降序","正序倒序"],
  "spinner": ["加载圈","Loading Spinner"],
  "split-screen-layout": ["分屏","Split Screen","Split-screen Layout"],
  "spring": ["弹簧动画","回弹动效","Spring Animation"],
  "sql": ["SQL 查询","结构化查询语言"],
  "staging": ["Staging","Staging Environment","预发布环境","预生产环境","准生产环境"],
  "state": ["UI 状态","界面状态","UI State","组件状态","State Management","状态管理"],
  "stateless-request": ["无状态 API"],
  "steps": ["Stepper","步骤指示器","流程步骤条"],
  "streaming-response": ["Streaming","流式输出"],
  "structured-output": ["响应格式"],
  "style-art-deco": ["装饰艺术运动","装饰艺术风格"],
  "style-bauhaus": ["包豪斯风格","包豪斯学派"],
  "style-y2k": ["Y2K 千禧风","千禧风"],
  "sub-agent": ["子 Agent","子智能体","Worker Agent"],
  "switch": ["Toggle","拨动开关","切换开关"],
  "system-prompt": ["系统指令","System Instructions"],
  "tailwind-css": ["Tailwind"],
  "tech-stack": ["技术选型","开发栈"],
  "test-case": ["Test Case","测试案例"],
  "test-coverage": ["Test Coverage","Code Coverage","代码覆盖率","Coverage"],
  "test-double": ["Test Double","Mock","测试替身","Stub","Fake","Spy"],
  "test-fixture": ["Test Fixture","Fixture","测试夹具","测试数据"],
  "thread": ["执行线程","工作线程","子线程","并发线程"],
  "time-picker": ["TimePicker"],
  "title-tag": ["title 元素","HTML title","浏览器标题"],
  "token": ["词元","文本令牌"],
  "token-cost": ["Token 费用","模型调用成本"],
  "tool-calling": ["Function Calling","函数调用"],
  "tooltip": ["文字提示","气泡提示","提示标签"],
  "transaction": ["数据库事务","DB 事务","ACID 事务"],
  "transition": ["平滑过渡","过渡效果","CSS过渡"],
  "tree-select": ["TreeSelect"],
  "typescript": ["TS"],
  "typography": ["文字排版","文本样式"],
  "undo": ["撤回","回退一步","Ctrl+Z"],
  "unit-test": ["单元测试","单测","UT"],
  "upload": ["文件上传","上传控件"],
  "url": ["网址","网页地址"],
  "use-case": ["用例","System Use Case","系统用例","使用案例"],
  "user-flow": ["用户流","UX Flow","用户流程图","User Flow Chart"],
  "user-journey": ["用户旅程图","客户旅程图","User Journey Map","Customer Journey","Customer Journey Map"],
  "user-story": ["用户叙事","User Stories","故事卡"],
  "user-voice": ["用户原声","用户反馈","用户之声","Testimonial"],
  "vibe-coding": ["氛围编程","凭感觉编程"],
  "video": ["视频播放器","嵌入视频"],
  "visual-hierarchy": ["信息层级","视觉优先级"],
  "vue": ["Vue.js"],
  "web-app-manifest": ["Manifest","manifest.json","Web 应用清单文件"],
  "web-hosting": ["网站主机","Hosting"],
  "wireframe": ["线框","原型草图","页面草图","低保真原型"],
  "xml-sitemap": ["sitemap.xml","XML 网站地图"],
  "z-index": ["层叠顺序","层级","Z轴层级","深度层级"],
};

export const aliasesFor = (id) => termAliases[id] || [];
